name: pdf_checker
description: A pure Dart package to check if PDF files are password-protected and to verify passwords.
version: 0.1.0
repository: https://github.com/RajKavadia/pdfchecker

environment:
  sdk: '>=2.12.0 <4.0.0' # Adjust SDK version as needed

  # Add dart_pdf_reader in the next step
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
